### ISSUE TITLE
Service Code Review

### ISSUE THREAD

**Issue by jghibiki** [jghibiki/mopey#61]
- [ ] Break logic out into methods instead of one giant loop of code. Makes the code much more readable.

---
- [ ] Additionally, all fun and games aside `DJPon3` is not an appropriate name for variables and there are no `turntables`. `SYSTEM` would be a logical username and would help prevent admins from tampering with it without instruction not to. Any justification for why we would leave `DJPon3`?

---
- [ ] What is the purpose of the `sys.stdout.flush()` I don't have a problem with it as long as it doesn't mess with the docker-compose logging, and by that I mean creates large gaps that you have to scroll past because it is the equivalent of calling `clear` in a terminal.

---
- [ ] There is the issue #59 which needs to be fixed as it could be a pretty simple but irritating bug when the timing issue happens.

---
- [ ] Try to use comments that actually help others - not just yourself - figure out what went wrong:

``` python
print "Token verification failed, retrieving new token"
```

instead of 

``` python
print "DJPon3's turntable broke down. fixing..."
```

---
- [ ] [This call](https://github.com/jghibiki/mopey/blob/master/service/src/Service.py#L31) should be placed right after receiving the api token as there are currently several api calls that in the future will likely require an admin.

---
- [ ] issue #60

**Comment by jghibiki** [comment]
As each issue is resolved i will check it off.

**Comment by jghibiki** [comment]
opens #22

**Comment by JPisaBrony** [comment]
DJPon3 and the print statements were my way of making working on it more fun, because if your going to code, why not throw in some humorous statements, variables, and comments for the dev team?
print "DJPon3's turntable broke down. fixing..."
was originally:
print "DJPon3's logged out and the turntable stopped turning, logging back in"
or something like that, but I wanted to make it more "interesting"
but besides that, a DJ is the person changing the songs so I though it was fitting, I just ponified it

sys.stdout.flush() is a C thing, if you don't have it, you get no output because the program is waiting to finish before printing anything and since we are using an infinite loop, you would never get output inless it crashes.
more info here:
https://stackoverflow.com/questions/13667625/print-statement-wont-print-before-an-infinite-loop

**Comment by jghibiki** [comment]
> sys.stdout.flush() is a C thing, [...]

Have you tried it without the sys.stdout.flush()? I'm almost certain python doesn't need it.

> DJ is the person changing the songs so I though it was fitting, I just ponified it

Could we compromise with `SYSTEM_DJ`? Like i said before i'd be concerned that leaving this funny looking DJPon3 alone would become a training issue and people would start messing with it. Additionally it's not super descriptive.

**Comment by JPisaBrony** [comment]
SYSTEM_DJ works

Have you tried it without the sys.stdout.flush()? I'm almost certain python doesn't need it.
yes, it doesn't work. it has to be explicit to work every time, when I was testing, it only sometimes did the print statements

**Comment by jghibiki** [comment]
> yes, it doesn't work. it has to be explicit to work every time, when I was testing, it only sometimes did the print statements

Hmmm, do you think we could trick it by adding something like:

``` python
quit = False

while not quit:
    pass
```

**Comment by jghibiki** [comment]
If not i would suggest just creating a helper method:

``` python
def printl(msg):
    print msg
    sys.stdout.flush()
```

I'm willing to bet the issue has something to do with docker's log buffereing

**Comment by JPisaBrony** [comment]
I don't know python well enough to know, I just know the C reason, but I will try the while loop suggestion.
